version: 2.1

orbs:
  node: circleci/node@5

jobs:
  lint_code:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run lint:fix

  test_code:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test

  build_code:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run build

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: "#e.g. ./deploy.sh"

workflows:
  build_app_and_deploy:
    jobs:
      - lint_code
      - test_code:
          requires:
            - lint_code
      - build_code:
          requires:
            - test_code